In [8]:
from sklearn.datasets import load_iris
from sklearn.kernel_ridge import KernelRidge
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np

This is all duplicated from the Basic Regression package, so the confirmation that it works has been omitted

In [9]:
regression_data = np.genfromtxt('ENB2012_data.csv', delimiter=',')
regression_data = np.delete(regression_data,(0), axis=0)
regression_inputs = np.take(regression_data, (0,1,2,3,4,5,6,7), axis =1)
regression_targets = np.take(regression_data, (8,9), axis = 1)
inputs_train, inputs_test, targets_train, targets_test = train_test_split(regression_inputs, regression_targets, test_size=0.2, random_state=50)

In [12]:
KRR_Linear = KernelRidge(alpha=1.0, kernel='linear')
KRR_Linear.fit(inputs_train, targets_train)

KernelRidge(alpha=1.0, coef0=1, degree=3, gamma=None, kernel='linear',
            kernel_params=None)

In [14]:
#Note that RBF is the 
KRR_RBF = KernelRidge(alpha=1.0, kernel='rbf')
KRR_RBF.fit(inputs_train, targets_train)

KernelRidge(alpha=1.0, coef0=1, degree=3, gamma=None, kernel='rbf',
            kernel_params=None)

In [15]:
print(KRR_Linear.score(inputs_test,targets_test))
print(KRR_RBF.score(inputs_test,targets_test))
print(KRR_Linear.predict(inputs_test)[0:6,0])
print(KRR_RBF.predict(inputs_test)[0:6,0])
print(targets_test[0:6,0])

0.8846252771547017
0.897104345340964
[18.67861882 28.68078325  9.21970837 38.14800076 33.0653234  24.56175463]
[12.47240712 26.56093137 11.69169171 33.93330703 36.72997245 21.55337108]
[17.14 23.59 10.68 40.71 33.12 19.34]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
